### ISSUE TITLE
Should not install nodejs core modules

### ISSUE THREAD

**Issue by nantas** [unfold/gulpfile-install#3]
I have a `gulpfile.js` that starts with
```js
var Path = require('path');
```

And running `gulpfile-install` on windows will give me the following error:
```bash
npm ERR! 404 404 Not Found: path%3Bnpm
npm ERR! 404
npm ERR! 404 'path%3Bnpm' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.
```

The same kind of works on mac, but it will install core 'path' module as if it's an ordinary npm module, with some complaining warning about "Path is a core node module, blahblahblah".

It would be great if this package can bypass node core modules required in gulpfile.

**Comment by einarlove** [comment]
I've [updated this package](dffec764ca218f8491bded9e5e929fc81bbd4767) now so that it ignores all modules it can find in the global scope. I hope this solves the issue for you.

I do not possess a windows machine so I'm unable to thoroughly test this so if the problem persists just give me a notice.

**Comment by nantas** [comment]
I tested with the latest version.
Your approach will also ignore packages that also has a cli, such as "gulp".

If I uninstall gulp cli:
`npm uninstall gulp -g`
then
`gulpfile-install` will install local gulp for my project.

I'm not quite sure why `require('gulp')` return positive in your code if there's no gulp in local project. I tested with other modules with cli and they will be ignored as well.

**Comment by einarlove** [comment]
Not sure how to approach this issue to be honest. If you have an idea on how to solve this feel free to send a pull request.
